
export const metadata = {
  // title: 'Next.js',
  title:{
    // absolute: "Blog",
    default: "Megha Default Title",
    template: "%s | CodeEvolution"

  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: "1rem", backgroundColor: "lightblue" }}>
          <p>Header</p>
        </header>
        
        {children}

        <footer style={{ padding: "1rem", backgroundColor: "lightgreen" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
